import { spawn } from "node:child_process";
import readline from "node:readline";
const srv = spawn("node", [new URL("../../../mcp/server.mjs", import.meta.url).pathname], { stdio: ["pipe", "pipe", "inherit"] });
const rl = readline.createInterface({ input: srv.stdout });
const pending = new Map(); let nextId = 1;
rl.on("line", l => { const m = JSON.parse(l); if (pending.has(m.id)) { pending.get(m.id)(m); pending.delete(m.id); } });
const rpc = (method, params) => new Promise(res => { const id = nextId++; pending.set(id, res); srv.stdin.write(JSON.stringify({ jsonrpc: "2.0", id, method, params }) + "\n"); });
const call = async (name, args) => { const r = await rpc("tools/call", { name, arguments: args }); const t = r.result.content[0].text; return r.result.isError ? { error: t } : JSON.parse(t); };
await rpc("initialize", { protocolVersion: "2024-11-05", capabilities: {}, clientInfo: { name: "c", version: "0" } });
const deck = "Power stage with gate drive\nVIN in 0 DC 12\nL1 in sw 100u\nM1 sw g 0 0 IRF540\nVG g 0 PULSE(0 10 0 20n 20n 5u 10u)\nD1 sw out 1N5819\nC1 out 0 100u\nC2 in 0 10u\nRL out 0 50\nR1 g gg 100\nR2 gg 0 10k\nR3 out fb 10k\nR4 fb 0 2k\nQ1 gg b e 2N2222\nRB b 0 4.7k\nRE e 0 100\nU1 a b c d e f g h 7400\n.end";
const c = await call("pcb_create", { netlist: deck, packages: { R1: "0805", R2: "0603", R3: "1206", R4: "0805", RB: "0805", RE: "0805", D1: "sod123", C2: "0805" } });
console.log(c.error || `${c.parts} parts`);
await call("pcb_edit", { board_id: c.board_id, actions: [{ op: "flip", ref: "R2" }, { op: "flip", ref: "R3" }] });
console.log(JSON.stringify((await call("pcb_route", { board_id: c.board_id })).failed));
console.log(JSON.stringify((await call("pcb_edit", { board_id: c.board_id, actions: [{ op: "pour", layer: "B", net: "0" }, { op: "pour", layer: "F", net: "0", points: [[1, 1], [20, 1], [20, 10], [1, 10]] }] })).results?.map(r => [r.copper_mm2, r.pads_cut_off])));
const k = await call("pcb_check", { board_id: c.board_id }); console.log("check", JSON.stringify(k.counts));
const e = await call("pcb_export", { board_id: c.board_id, name: "gb", directory: process.argv[2], force: true });
console.log(JSON.stringify(e.files.map(f => f.name + ":" + f.bytes)), "board", JSON.stringify(c.board_mm));
await call("pcb_render", { board_id: c.board_id, file: process.argv[2] + "/gb.svg" });
import fs from "node:fs";
fs.writeFileSync(process.argv[2] + "/board.json", JSON.stringify((await call("pcb_describe", { board_id: c.board_id, include: ["json"] })).board_json));
srv.stdin.end();
